### ISSUE TITLE
NotFoundException: No binding found for bind<PhotoListPresenter>() with ? { ? }

### ISSUE THREAD

**Issue by nicopasso** [JorgeCastilloPrz/AndroidKodeinSample#3] opened 2018-09-18 07:54 UTC
Hi Jorge,
first of all thanks for the Kodein caster.io tutorial! 
I'm facing an issue right now though. I cloned your repo after writing the whole app by myself in a different project but on both projects I'm getting the same stacktrace:

```java
java.lang.RuntimeException: Unable to resume activity {me.jorgecastillo.kodein/me.jorgecastillo.kodein.photoslist.view.PhotoListActivity}: org.kodein.di.Kodein$NotFoundException: No binding found for bind<PhotoListPresenter>() with ? { ? }
    Registered in this Kodein container:
    
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: org.kodein.di.Kodein$NotFoundException: No binding found for bind<PhotoListPresenter>() with ? { ? }
    Registered in this Kodein container:
    
        at org.kodein.di.internal.KodeinContainerImpl.factory(KodeinContainerImpl.kt:174)
        at org.kodein.di.KodeinContainer$DefaultImpls.factory$default(KodeinContainer.kt:33)
        at org.kodein.di.KodeinContainer$DefaultImpls.provider(KodeinContainer.kt:80)
        at org.kodein.di.internal.KodeinContainerImpl.provider(KodeinContainerImpl.kt:7)
        at org.kodein.di.KodeinContainer$DefaultImpls.provider$default(KodeinContainer.kt:79)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:152)
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:39)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at me.jorgecastillo.kodein.photoslist.view.PhotoListActivity.getPresenter(PhotoListActivity.kt)
        at me.jorgecastillo.kodein.photoslist.view.PhotoListActivity.onResume(PhotoListActivity.kt:36)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
        at android.app.Activity.performResume(Activity.java:6783)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3406)
        	... 10 more
```

I wasn't able to find the reason behind it. guess it's due to the new 5.2 version of Kodein but I'm not entirely sure and I don't know Kodein enough to take a deeper look at it to find what's wrong.
Could you take a look at it?

**Comment by smitsgit** [comment] 2018-09-23 11:50
+1 yeh facing the same issue. Not sure what the problem is though 
`bind<PhotoListPresenter>() with provider { PhotoListPresenter(instance(), instance(), instance()) }`
  This is present to provide the binding.

**Comment by miibpa** [comment] 2018-11-27 11:26
I'm also having the same issue, any guess on how to solve this?

**Comment by JorgeCastilloPrz** [comment] 2018-12-16 08:12
This is fixed now. It got broken after upgrading to Kodein 5.0.0 last month. I've upgraded to Kodein 6.0.0 and fixed the but now. Please, pull and let me know if it's also working for you. Thanks!

**Closed as completed by JorgeCastilloPrz** 2018-12-16 08:12 UTC
